- include_tasks: chrome.yml
- include_tasks: filezilla.yml
- include_tasks: keepassxc.yml
- include_tasks: postman.yml
- include_tasks: drawio.yml
- include_tasks: rclone.yml
- include_tasks: google-cloud-sdk.yml
- include_tasks: kubectl.yml
- include_tasks: k9s.yml
- include_tasks: docker.yml