- include_tasks: chrome.yml
- include_tasks: vscode.yml
- include_tasks: filezilla.yml
- include_tasks: keepassxc.yml
- include_tasks: postman.yml
- include_tasks: drawio.yml
- include_tasks: rclone.yml